-- SQL to create tables and default admin password for project unique_popup
create table if not exists public.phrases (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz default now()
);

create table if not exists public.socials (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  icon_base64 text null,
  created_at timestamptz default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  event_type text not null,
  info jsonb null,
  visitor_id text null,
  created_at timestamptz default now()
);

-- insert default admin password (change '1234' after deployment)
insert into public.settings (key, value) values
('admin_password', '"1234"')
on conflict (key) do update set value = excluded.value;

-- insert default theme setting
insert into public.settings (key, value) values
('theme', '{"name":"theme-dark"}')
on conflict (key) do update set value = excluded.value;
